import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { api,apiErrorMessage } from '../services/api';

export function ManualBilling(){
  const client=useQueryClient();const [file,setFile]=useState<File|null>(null);const [reference,setReference]=useState('');const [payer,setPayer]=useState('');const [paidOn,setPaidOn]=useState('');const [draftId,setDraftId]=useState('');
  const query=useQuery({queryKey:['manual-billing'],queryFn:async()=> (await api.get<{instructions:string;qrUrl:string|null;requests:Array<{id:string;amount:number;currency:string;status:string;review_reason:string|null}>}>('/billing/manual')).data});
  const submit=useMutation({mutationFn:async()=>{let id=draftId;if(!id){if(!file||file.size>5242880||!['image/jpeg','image/png','application/pdf'].includes(file.type))throw new Error('Selecciona un PDF, JPG o PNG de hasta 5 MB.');const {data}=await api.post<{id:string;signedUrl:string}>('/billing/manual');id=data.id;const body=new FormData();body.append('cacheControl','0');body.append('',file);const result=await fetch(data.signedUrl,{method:'PUT',headers:{'x-upsert':'true'},body});if(!result.ok)throw new Error('No se pudo subir el comprobante.');setDraftId(id);}await api.post(`/billing/manual/${id}/submit`,{reference,payer,paidOn});},onSuccess:async()=>{setDraftId('');setFile(null);await client.invalidateQueries({queryKey:['manual-billing']});}});
  const labels:Record<string,string>={draft:'Preparando',pending:'Pendiente de revisión',approved:'Aprobado',rejected:'Rechazado'};
  return <section className="panel"><h2>Pagar por transferencia</h2>{query.isLoading?<p>Cargando datos…</p>:query.isError?<div className="alert error">{apiErrorMessage(query.error)}</div>:<><div className="manual-payment-details">{query.data?.qrUrl&&<img src={query.data.qrUrl} alt="QR de pago de FitLab"/>}<p>{query.data?.instructions||'Los datos de transferencia todavía no están disponibles.'}</p></div><p>Sube el comprobante y revisaremos el ingreso. La activación se realiza al aprobar el pago.</p>{query.data?.instructions&&!query.data.requests.some(r=>r.status==='pending')&&<form onSubmit={e=>{e.preventDefault();submit.mutate();}} className="checkout-form single"><label>Comprobante (PDF, JPG o PNG, hasta 5 MB)<input type="file" accept="image/jpeg,image/png,application/pdf" disabled={!!draftId||submit.isPending} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label>Nombre del pagador<input required minLength={2} maxLength={150} value={payer} onChange={e=>setPayer(e.target.value)}/></label><label>Referencia de la transferencia<input required minLength={4} maxLength={120} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Fecha del pago<input type="date" required max={new Date().toISOString().slice(0,10)} value={paidOn} onChange={e=>setPaidOn(e.target.value)}/></label><button className="primary" disabled={submit.isPending||(!file&&!draftId)}>{submit.isPending?'Enviando…':'Enviar a revisión'}</button></form>}{submit.isError&&<div className="alert error">{apiErrorMessage(submit.error)}</div>}{query.data?.requests.map(r=><article key={r.id}><p><strong>{labels[r.status]}</strong> · {Number(r.amount).toFixed(2)} {r.currency}</p><small>Orden: {r.id}</small>{r.review_reason&&<p>{r.review_reason}</p>}</article>)}</>}</section>;
}
