import { Router } from 'express';
import { changePromotionStatus, claimReward, getLoyalty, listPromotions, redeemProduct, revokeReward, savePromotion } from '../controllers/loyalty.controller.js';
import { verifyJWT } from '../middlewares/verifyJWT.js';
import { tenantContext } from '../middlewares/tenantContext.js';
import { requireOwner } from '../middlewares/requireOwner.js';
import { databaseRateLimit } from '../middlewares/rateLimit.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { getEngagement, createReferralCode, attachReferral, savePreferences, readNotification, evaluateLoyalty, getAnalytics } from '../controllers/loyalty.controller.js';

export const loyaltyRouter = Router();
loyaltyRouter.use(verifyJWT, tenantContext);
const mutationLimit = databaseRateLimit({ bucket: 'loyalty.write', maximumHits: 60, windowSeconds: 60, subject: (request) => `${request.tenant!.gymId}:${request.tenant!.gymUserId}` });
loyaltyRouter.get('/me', asyncHandler(getLoyalty));
loyaltyRouter.get('/me/engagement', asyncHandler(getEngagement));
loyaltyRouter.post('/me/referral-code', mutationLimit, asyncHandler(createReferralCode));
loyaltyRouter.post('/me/referrals', mutationLimit, asyncHandler(attachReferral));
loyaltyRouter.put('/me/notification-preferences', mutationLimit, asyncHandler(savePreferences));
loyaltyRouter.post('/me/notifications/:id/read', mutationLimit, asyncHandler(readNotification));
loyaltyRouter.post('/me/promotions/:id/claim', mutationLimit, asyncHandler(claimReward));
loyaltyRouter.use(requireOwner);
loyaltyRouter.get('/analytics', asyncHandler(getAnalytics));
loyaltyRouter.post('/evaluate', mutationLimit, asyncHandler(evaluateLoyalty));
loyaltyRouter.get('/members/:memberId/engagement', asyncHandler(getEngagement));
loyaltyRouter.post('/members/:memberId/referrals', mutationLimit, asyncHandler(attachReferral));
loyaltyRouter.get('/promotions', asyncHandler(listPromotions));
loyaltyRouter.get('/members/:memberId', asyncHandler(getLoyalty));
loyaltyRouter.post('/members/:memberId/promotions/:id/claim', mutationLimit, asyncHandler(claimReward));
loyaltyRouter.post('/promotions', mutationLimit, asyncHandler(savePromotion));
loyaltyRouter.put('/promotions/:id', mutationLimit, asyncHandler(savePromotion));
loyaltyRouter.patch('/promotions/:id/status', mutationLimit, asyncHandler(changePromotionStatus));
loyaltyRouter.post('/rewards/:id/redeem-product', mutationLimit, asyncHandler(redeemProduct));
loyaltyRouter.post('/rewards/:id/revoke', mutationLimit, asyncHandler(revokeReward));
