import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ban, CalendarPlus, Check, ClipboardCheck, Dumbbell, FileText, LoaderCircle, Plus, ReceiptText, RotateCcw, UserPlus, Users, X } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { useAuth } from '../context/AuthContext';
import { api, apiErrorMessage } from '../services/api';

type ActivityItem = { id: string; name: string; description?: string | null; billing_mode: 'included' | 'additional_fee'; price: number; currency: string; capacity: number; duration_minutes: number; is_active: boolean };
type Location = { id: string; name: string; is_main?: boolean; timezone: string };
type Person = { id: string; name: string; phone?: string | null; defaultLocationId?: string | null };
type Booking = { id: string; class_schedule_id: string; member_user_id: string; status: 'reserved' | 'attended' | 'cancelled' | 'no_show'; payment_id?: string | null; booked_at: string; cancellation_reason?: string | null; member: Person; payment?: { id: string; amount: number; currency: string; payment_method: string; status: string; receipt_number: number } | null };
type Schedule = { id: string; location_id: string; extra_class_id: string; instructor_user_id?: string | null; starts_at: string; ends_at: string; status: 'scheduled' | 'cancelled' | 'completed'; cancellation_reason?: string | null; activity: ActivityItem; location: Location; instructor?: Person | null; occupied: number; capacity: number; available: number };
type ActivitiesResponse = { access: { manage: boolean; bookings: boolean; attendance: boolean }; activities: ActivityItem[]; locations: Location[]; instructors: Person[]; members: Person[]; schedules: Schedule[]; bookings: Booking[] };
type Receipt = { number: number; issuedAt: string; status: string; amount: number; currency: string; paymentMethod: string; externalReference?: string | null; paidAt: string; refundReason?: string | null; gym: { name: string; legal_name?: string | null }; location: { name: string; address?: string | null; city?: string | null }; member: Person; activity: ActivityItem; schedule: { startsAt: string; endsAt: string }; instructor?: Person | null; registeredBy: Person; bookingStatus: string };
type ActivityForm = { name: string; description: string; billingMode: 'included' | 'additional_fee'; price: string; currency: string; capacity: string; durationMinutes: string; isActive: boolean };
type ScheduleForm = { activityId: string; locationId: string; instructorUserId: string; startsAt: string; capacityOverride: string };
type BookingForm = { memberUserId: string; method: 'cash' | 'bank_transfer' | 'external_card' | 'external_deuna' | 'other'; externalReference: string; notes: string };

const emptyActivity: ActivityForm = { name: '', description: '', billingMode: 'included', price: '0', currency: 'USD', capacity: '12', durationMinutes: '60', isActive: true };
const emptySchedule: ScheduleForm = { activityId: '', locationId: '', instructorUserId: '', startsAt: '', capacityOverride: '' };
const emptyBooking: BookingForm = { memberUserId: '', method: 'cash', externalReference: '', notes: '' };
const money = (value: number, currency: string) => new Intl.NumberFormat('es-EC', { style: 'currency', currency }).format(Number(value));
const dateTime = (value: string) => new Intl.DateTimeFormat('es-EC', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const paymentNames: Record<string, string> = { cash: 'Efectivo', bank_transfer: 'Transferencia', external_card: 'Tarjeta', external_deuna: 'Deuna', other: 'Otro' };
const bookingNames: Record<string, string> = { reserved: 'Reservada', attended: 'Asistió', cancelled: 'Cancelada', no_show: 'No asistió' };

export function ActivitiesPage() {
  const { session } = useAuth();
  const client = useQueryClient();
  const role = session?.gymUser?.role;
  const permission = (key: string) => role === 'owner' || Boolean(session?.gymUser?.staff_permissions?.some((item) => item.permission_key === key && item.access_mode !== 'denied'));
  const canManage = permission('classes.manage');
  const canBook = permission('classes.bookings_manage');
  const canAttend = permission('classes.attendance_manage');
  const canRefund = permission('payments.void') && canBook;
  const [tab, setTab] = useState<'agenda' | 'catalog' | 'bookings'>('agenda');
  const [locationId, setLocationId] = useState(session?.gymUser?.default_location_id ?? '');
  const [selectedScheduleId, setSelectedScheduleId] = useState('');
  const [activityTarget, setActivityTarget] = useState<ActivityItem | null | undefined>(undefined);
  const [activityForm, setActivityForm] = useState<ActivityForm>(emptyActivity);
  const [scheduleOpen, setScheduleOpen] = useState(false);
  const [scheduleForm, setScheduleForm] = useState<ScheduleForm>(emptySchedule);
  const [bookingSchedule, setBookingSchedule] = useState<Schedule | null>(null);
  const [bookingForm, setBookingForm] = useState<BookingForm>(emptyBooking);
  const [reasonAction, setReasonAction] = useState<{ type: 'schedule' | 'booking' | 'refund'; id: string; title: string } | null>(null);
  const [reason, setReason] = useState('');
  const [receiptBookingId, setReceiptBookingId] = useState<string | null>(null);
  const [error, setError] = useState('');

  const activities = useQuery({ queryKey: ['activities', locationId, canManage], queryFn: async () => (await api.get<ActivitiesResponse>('/activities', { params: { locationId: locationId || undefined, includeInactive: canManage ? 'true' : 'false' } })).data });
  const receipt = useQuery({ queryKey: ['class-receipt', receiptBookingId], enabled: Boolean(receiptBookingId), queryFn: async () => (await api.get<{ receipt: Receipt }>(`/activities/bookings/${receiptBookingId}/receipt`)).data.receipt });
  const data = activities.data;
  const selectedSchedule = data?.schedules.find((item) => item.id === selectedScheduleId) ?? data?.schedules[0];
  const selectedBookings = useMemo(() => (data?.bookings ?? []).filter((item) => item.class_schedule_id === selectedSchedule?.id), [data?.bookings, selectedSchedule?.id]);

  useEffect(() => { if (selectedSchedule && selectedSchedule.id !== selectedScheduleId) setSelectedScheduleId(selectedSchedule.id); }, [selectedSchedule, selectedScheduleId]);
  const refresh = async () => { await client.invalidateQueries({ queryKey: ['activities'] }); };

  const saveActivity = useMutation({
    mutationFn: async () => {
      const payload = { name: activityForm.name, description: activityForm.description || null, billingMode: activityForm.billingMode, price: Number(activityForm.price), currency: activityForm.currency.toUpperCase(), capacity: Number(activityForm.capacity), durationMinutes: Number(activityForm.durationMinutes), isActive: activityForm.isActive };
      return activityTarget ? api.put(`/activities/catalog/${activityTarget.id}`, payload) : api.post('/activities/catalog', payload);
    },
    onSuccess: async () => { setActivityTarget(undefined); setActivityForm(emptyActivity); setError(''); await refresh(); },
    onError: (cause) => setError(apiErrorMessage(cause)),
  });
  const createSchedule = useMutation({
    mutationFn: async () => api.post('/activities/schedules', { activityId: scheduleForm.activityId, locationId: scheduleForm.locationId, instructorUserId: scheduleForm.instructorUserId || null, startsAt: new Date(scheduleForm.startsAt).toISOString(), capacityOverride: scheduleForm.capacityOverride ? Number(scheduleForm.capacityOverride) : null }),
    onSuccess: async () => { setScheduleOpen(false); setScheduleForm(emptySchedule); setError(''); await refresh(); },
    onError: (cause) => setError(apiErrorMessage(cause)),
  });
  const createBooking = useMutation({
    mutationFn: async () => {
      if (!bookingSchedule) return;
      const paid = bookingSchedule.activity.billing_mode === 'additional_fee';
      return api.post(`/activities/schedules/${bookingSchedule.id}/bookings`, { memberUserId: bookingForm.memberUserId, payment: paid ? { method: bookingForm.method, externalReference: bookingForm.externalReference || null, notes: bookingForm.notes || null } : null });
    },
    onSuccess: async () => { setBookingSchedule(null); setBookingForm(emptyBooking); setError(''); await refresh(); },
    onError: (cause) => setError(apiErrorMessage(cause)),
  });
  const runReasonAction = useMutation({
    mutationFn: async () => {
      if (!reasonAction) return;
      if (reasonAction.type === 'schedule') return api.patch(`/activities/schedules/${reasonAction.id}/cancel`, { reason });
      return api.patch(`/activities/bookings/${reasonAction.id}/${reasonAction.type === 'refund' ? 'refund' : 'cancel'}`, { reason });
    },
    onSuccess: async () => { setReasonAction(null); setReason(''); setError(''); await refresh(); },
    onError: (cause) => setError(apiErrorMessage(cause)),
  });
  const attendance = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: 'attended' | 'no_show' }) => api.patch(`/activities/bookings/${id}/attendance`, { status }),
    onSuccess: refresh,
    onError: (cause) => setError(apiErrorMessage(cause)),
  });

  const openActivity = (item?: ActivityItem) => {
    setError(''); setActivityTarget(item ?? null);
    setActivityForm(item ? { name: item.name, description: item.description ?? '', billingMode: item.billing_mode, price: String(item.price), currency: item.currency, capacity: String(item.capacity), durationMinutes: String(item.duration_minutes), isActive: item.is_active } : emptyActivity);
  };
  const openSchedule = () => {
    setScheduleForm({ ...emptySchedule, activityId: data?.activities.find((item) => item.is_active)?.id ?? '', locationId: locationId || data?.locations[0]?.id || '' });
    setScheduleOpen(true); setError('');
  };
  const submitActivity = (event: FormEvent) => { event.preventDefault(); saveActivity.mutate(); };
  const submitSchedule = (event: FormEvent) => { event.preventDefault(); createSchedule.mutate(); };
  const submitBooking = (event: FormEvent) => { event.preventDefault(); createBooking.mutate(); };
  const submitReason = (event: FormEvent) => { event.preventDefault(); runReasonAction.mutate(); };
  const futureSchedules = data?.schedules.filter((item) => new Date(item.ends_at).getTime() >= Date.now()) ?? [];
  const activeActivities = data?.activities.filter((item) => item.is_active).length ?? 0;
  const reservedCount = data?.bookings.filter((item) => item.status === 'reserved').length ?? 0;

  return <div className="page activities-page">
    <div className="page-heading"><div><p className="eyebrow">EXPERIENCIAS DEL GIMNASIO</p><h1>ACTIVIDADES</h1><p>Programa clases, administra cupos y permite reservas sin mezclar su llegada con el QR general.</p></div><Dumbbell size={42}/></div>
    {error && <div className="alert error"><span>{error}</span><button className="icon-button" onClick={() => setError('')}><X/></button></div>}
    <section className="panel activities-toolbar"><label>Sucursal<select value={locationId} onChange={(event) => setLocationId(event.target.value)}><option value="">Todas las sucursales</option>{data?.locations.map((item) => <option value={item.id} key={item.id}>{item.name}{item.is_main ? ' · Principal' : ''}</option>)}</select></label><div className="activity-kpis"><span><Dumbbell/>{activeActivities} actividades</span><span><CalendarPlus/>{futureSchedules.length} clases próximas</span><span><Users/>{reservedCount} reservas</span></div></section>
    <section className="panel activities-panel"><div className="directory-tabs activity-tabs"><button className={tab === 'agenda' ? 'active' : ''} onClick={() => setTab('agenda')}><CalendarPlus/>Agenda</button>{canManage && <button className={tab === 'catalog' ? 'active' : ''} onClick={() => setTab('catalog')}><Dumbbell/>Catálogo</button>}<button className={tab === 'bookings' ? 'active' : ''} onClick={() => setTab('bookings')}><ClipboardCheck/>Reservas <span>{data?.bookings.length ?? 0}</span></button></div>
      {activities.isLoading ? <Loading/> : activities.isError ? <div className="empty compact"><Ban/><strong>{apiErrorMessage(activities.error)}</strong></div> : <>
        {tab === 'agenda' && <div className="activity-agenda"><div className="schedule-column"><div className="commerce-actions"><div><h2>Próximas clases</h2><p>Selecciona una clase para consultar su lista.</p></div>{canManage && <button className="primary" onClick={openSchedule}><Plus/>Programar clase</button>}</div><div className="schedule-cards">{futureSchedules.map((item) => <button key={item.id} className={`schedule-card ${selectedSchedule?.id === item.id ? 'selected' : ''}`} onClick={() => setSelectedScheduleId(item.id)}><span className="schedule-date"><b>{new Date(item.starts_at).toLocaleDateString('es-EC', { day: '2-digit' })}</b><small>{new Date(item.starts_at).toLocaleDateString('es-EC', { month: 'short' })}</small></span><span><strong>{item.activity.name}</strong><small>{dateTime(item.starts_at)} · {item.location?.name}</small><small>{item.instructor?.name ?? 'Sin instructor asignado'}</small></span><span><b>{item.occupied}/{item.capacity}</b><small>cupos</small></span></button>)}{!futureSchedules.length && <Empty title="No hay clases programadas" text="Crea una fecha para comenzar a recibir reservas."/>}</div></div><Roster schedule={selectedSchedule} bookings={selectedBookings} canManage={canManage} canBook={canBook} canAttend={canAttend} canRefund={canRefund} onBook={(schedule) => { setBookingSchedule(schedule); setBookingForm(emptyBooking); }} onCancelSchedule={(schedule) => { setReasonAction({ type: 'schedule', id: schedule.id, title: `Cancelar ${schedule.activity.name}` }); setReason(''); }} onCancelBooking={(booking) => { setReasonAction({ type: 'booking', id: booking.id, title: `Cancelar reserva de ${booking.member.name}` }); setReason(''); }} onRefund={(booking) => { setReasonAction({ type: 'refund', id: booking.id, title: `Reembolsar a ${booking.member.name}` }); setReason(''); }} onAttendance={(id, status) => attendance.mutate({ id, status })} onReceipt={setReceiptBookingId}/></div>}
        {tab === 'catalog' && canManage && <><div className="commerce-actions"><div><h2>Catálogo de actividades</h2><p>Una actividad incluida vale 0; una actividad adicional se cobra al reservar.</p></div><button className="primary" onClick={() => openActivity()}><Plus/>Nueva actividad</button></div><div className="activity-catalog">{data?.activities.map((item) => <article key={item.id}><div className="activity-card-top"><Dumbbell/><span className={`badge ${item.is_active ? 'active' : 'inactive'}`}>{item.is_active ? 'Activa' : 'Inactiva'}</span></div><h3>{item.name}</h3><p>{item.description || 'Sin descripción'}</p><div className="activity-card-meta"><span><b>{item.capacity}</b> cupos</span><span><b>{item.duration_minutes}</b> min</span><strong>{item.billing_mode === 'included' ? 'Incluida en membresía' : money(item.price, item.currency)}</strong></div><button className="small-button" onClick={() => openActivity(item)}>Editar</button></article>)}</div></>}
        {tab === 'bookings' && <><div className="commerce-actions"><div><h2>Historial de reservas</h2><p>La asistencia a clases se controla aquí; no crea una entrada general por QR.</p></div></div><div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Miembro</th><th>Actividad</th><th>Fecha</th><th>Pago</th><th>Estado</th></tr></thead><tbody>{data?.bookings.map((booking) => { const schedule = data.schedules.find((item) => item.id === booking.class_schedule_id); return <tr key={booking.id}><td><strong>{booking.member.name}</strong><small>{booking.member.phone || 'Sin teléfono'}</small></td><td>{schedule?.activity.name ?? 'Actividad'}</td><td>{schedule ? dateTime(schedule.starts_at) : '—'}</td><td>{booking.payment ? `${money(booking.payment.amount, booking.payment.currency)} · ${paymentNames[booking.payment.payment_method] ?? booking.payment.payment_method}` : 'Incluida'}</td><td><span className={`badge ${booking.status}`}>{bookingNames[booking.status]}</span></td></tr>; })}</tbody></table>{!data?.bookings.length && <Empty title="Sin reservas" text="Las reservas aparecerán cuando un miembro elija una clase."/>}</div></>}
      </>}</section>
    {activityTarget !== undefined && <div className="modal-backdrop"><form className="modal commerce-modal" onSubmit={submitActivity}><header><div><p className="eyebrow">CATÁLOGO</p><h2>{activityTarget ? 'Editar actividad' : 'Nueva actividad'}</h2></div><button type="button" className="icon-button" onClick={() => setActivityTarget(undefined)}><X/></button></header><div className="commerce-form"><label>Nombre<input required minLength={2} maxLength={120} value={activityForm.name} onChange={(event) => setActivityForm({ ...activityForm, name: event.target.value })}/></label><label>Descripción<textarea maxLength={1000} value={activityForm.description} onChange={(event) => setActivityForm({ ...activityForm, description: event.target.value })}/></label><div className="form-grid"><label>Cobro<select value={activityForm.billingMode} onChange={(event) => { const billingMode = event.target.value as ActivityForm['billingMode']; setActivityForm({ ...activityForm, billingMode, price: billingMode === 'included' ? '0' : activityForm.price === '0' ? '' : activityForm.price }); }}><option value="included">Incluida en membresía</option><option value="additional_fee">Pago adicional</option></select></label><label>Precio<input required type="number" min={activityForm.billingMode === 'included' ? 0 : 0.01} step="0.01" disabled={activityForm.billingMode === 'included'} value={activityForm.price} onChange={(event) => setActivityForm({ ...activityForm, price: event.target.value })}/></label><label>Cupos<input required type="number" min="1" value={activityForm.capacity} onChange={(event) => setActivityForm({ ...activityForm, capacity: event.target.value })}/></label><label>Duración (minutos)<input required type="number" min="10" value={activityForm.durationMinutes} onChange={(event) => setActivityForm({ ...activityForm, durationMinutes: event.target.value })}/></label></div>{activityTarget && <label className="checkbox-line"><input type="checkbox" checked={activityForm.isActive} onChange={(event) => setActivityForm({ ...activityForm, isActive: event.target.checked })}/>Actividad disponible</label>}<div className="modal-actions"><button type="button" className="ghost" onClick={() => setActivityTarget(undefined)}>Cancelar</button><button className="primary" disabled={saveActivity.isPending}>{saveActivity.isPending ? <LoaderCircle className="spin"/> : <Check/>}Guardar</button></div></div></form></div>}
    {scheduleOpen && <div className="modal-backdrop"><form className="modal commerce-modal" onSubmit={submitSchedule}><header><div><p className="eyebrow">AGENDA</p><h2>Programar clase</h2></div><button type="button" className="icon-button" onClick={() => setScheduleOpen(false)}><X/></button></header><div className="commerce-form"><label>Actividad<select required value={scheduleForm.activityId} onChange={(event) => setScheduleForm({ ...scheduleForm, activityId: event.target.value })}><option value="">Selecciona</option>{data?.activities.filter((item) => item.is_active).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Sucursal<select required value={scheduleForm.locationId} onChange={(event) => setScheduleForm({ ...scheduleForm, locationId: event.target.value })}><option value="">Selecciona</option>{data?.locations.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Instructor<select value={scheduleForm.instructorUserId} onChange={(event) => setScheduleForm({ ...scheduleForm, instructorUserId: event.target.value })}><option value="">Sin asignar</option>{data?.instructors.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="form-grid"><label>Fecha y hora<input required type="datetime-local" value={scheduleForm.startsAt} onChange={(event) => setScheduleForm({ ...scheduleForm, startsAt: event.target.value })}/></label><label>Cupos especiales<input type="number" min="1" placeholder="Usar capacidad normal" value={scheduleForm.capacityOverride} onChange={(event) => setScheduleForm({ ...scheduleForm, capacityOverride: event.target.value })}/></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={() => setScheduleOpen(false)}>Cancelar</button><button className="primary" disabled={createSchedule.isPending}>{createSchedule.isPending ? <LoaderCircle className="spin"/> : <CalendarPlus/>}Programar</button></div></div></form></div>}
    {bookingSchedule && <div className="modal-backdrop"><form className="modal commerce-modal" onSubmit={submitBooking}><header><div><p className="eyebrow">RESERVA EN RECEPCIÓN</p><h2>{bookingSchedule.activity.name}</h2></div><button type="button" className="icon-button" onClick={() => setBookingSchedule(null)}><X/></button></header><div className="commerce-form"><p className="activity-booking-note">{dateTime(bookingSchedule.starts_at)} · {bookingSchedule.available} cupos disponibles</p><label>Miembro<select required value={bookingForm.memberUserId} onChange={(event) => setBookingForm({ ...bookingForm, memberUserId: event.target.value })}><option value="">Selecciona un miembro</option>{data?.members.map((item) => <option value={item.id} key={item.id}>{item.name}{item.phone ? ` · ${item.phone}` : ''}</option>)}</select></label>{bookingSchedule.activity.billing_mode === 'additional_fee' && <><div className="activity-payment-summary"><span>Pago de la actividad</span><strong>{money(bookingSchedule.activity.price, bookingSchedule.activity.currency)}</strong></div><label>Método de pago<select value={bookingForm.method} onChange={(event) => setBookingForm({ ...bookingForm, method: event.target.value as BookingForm['method'] })}><option value="cash">Efectivo</option><option value="bank_transfer">Transferencia</option><option value="external_card">Tarjeta</option><option value="external_deuna">Deuna</option><option value="other">Otro</option></select></label>{['bank_transfer','external_card','external_deuna'].includes(bookingForm.method) && <label>Referencia<input required maxLength={200} value={bookingForm.externalReference} onChange={(event) => setBookingForm({ ...bookingForm, externalReference: event.target.value })}/></label>}<label>Notas<textarea maxLength={1000} value={bookingForm.notes} onChange={(event) => setBookingForm({ ...bookingForm, notes: event.target.value })}/></label></>}<div className="modal-actions"><button type="button" className="ghost" onClick={() => setBookingSchedule(null)}>Cancelar</button><button className="primary" disabled={createBooking.isPending}>{createBooking.isPending ? <LoaderCircle className="spin"/> : <UserPlus/>}{bookingSchedule.activity.billing_mode === 'additional_fee' ? 'Cobrar y reservar' : 'Reservar'}</button></div></div></form></div>}
    {reasonAction && <div className="modal-backdrop"><form className="modal commerce-modal" onSubmit={submitReason}><header><div><p className="eyebrow">ACCIÓN CON HISTORIAL</p><h2>{reasonAction.title}</h2></div><button type="button" className="icon-button" onClick={() => setReasonAction(null)}><X/></button></header><div className="commerce-form"><label>Motivo<textarea autoFocus required minLength={3} maxLength={500} value={reason} onChange={(event) => setReason(event.target.value)}/></label><div className="modal-actions"><button type="button" className="ghost" onClick={() => setReasonAction(null)}>Volver</button><button className="danger-button" disabled={runReasonAction.isPending}>{reasonAction.type === 'refund' ? <RotateCcw/> : <Ban/>}{reasonAction.type === 'refund' ? 'Reembolsar' : 'Confirmar cancelación'}</button></div></div></form></div>}
    {receiptBookingId && <div className="modal-backdrop"><section className="modal commerce-modal"><header><div><p className="eyebrow">COMPROBANTE INTERNO</p><h2>Recibo de actividad</h2></div><button className="icon-button" onClick={() => setReceiptBookingId(null)}><X/></button></header>{receipt.isLoading ? <Loading/> : receipt.data ? <div className="class-receipt"><div><strong>{receipt.data.gym.name}</strong><span>ACT-REC-{String(receipt.data.number).padStart(6, '0')}</span></div><p><b>{receipt.data.activity.name}</b><span>{dateTime(receipt.data.schedule.startsAt)} · {receipt.data.location.name}</span></p><p><b>{receipt.data.member.name}</b><span>{receipt.data.member.phone || 'Sin teléfono'}</span></p><p><b>Total</b><strong>{money(receipt.data.amount, receipt.data.currency)}</strong></p><small>Comprobante interno. No válido como comprobante tributario.</small><button className="primary full-width" onClick={() => window.print()}><FileText/>Imprimir</button></div> : <div className="alert error">{receipt.isError ? apiErrorMessage(receipt.error) : 'No se encontró el recibo.'}</div>}</section></div>}
  </div>;
}

function Roster({ schedule, bookings, canManage, canBook, canAttend, canRefund, onBook, onCancelSchedule, onCancelBooking, onRefund, onAttendance, onReceipt }: { schedule?: Schedule; bookings: Booking[]; canManage: boolean; canBook: boolean; canAttend: boolean; canRefund: boolean; onBook: (schedule: Schedule) => void; onCancelSchedule: (schedule: Schedule) => void; onCancelBooking: (booking: Booking) => void; onRefund: (booking: Booking) => void; onAttendance: (id: string, status: 'attended' | 'no_show') => void; onReceipt: (id: string) => void }) {
  if (!schedule) return <aside className="roster-panel"><Empty title="Selecciona una clase" text="Aquí verás sus participantes y acciones."/></aside>;
  return <aside className="roster-panel"><header><div><p className="eyebrow">LISTA DE CLASE</p><h2>{schedule.activity.name}</h2><span>{dateTime(schedule.starts_at)} · {schedule.location.name}</span><span>Instructor: {schedule.instructor?.name ?? 'Sin asignar'}</span></div><span className={`badge ${schedule.status}`}>{schedule.status === 'scheduled' ? 'Programada' : 'Cancelada'}</span></header><div className="roster-summary"><span><Users/><b>{schedule.occupied}</b> reservados</span><span><b>{schedule.available}</b> disponibles</span></div><div className="roster-list">{bookings.map((booking) => <article key={booking.id}><div><strong>{booking.member.name}</strong><small>{booking.member.phone || 'Sin teléfono'} · {booking.payment ? money(booking.payment.amount, booking.payment.currency) : 'Incluida'}</small></div><span className={`badge ${booking.status}`}>{bookingNames[booking.status]}</span><div className="row-actions">{booking.payment && <button className="small-button" onClick={() => onReceipt(booking.id)}><ReceiptText/>Recibo</button>}{canAttend && booking.status === 'reserved' && <><button className="small-button" onClick={() => onAttendance(booking.id, 'attended')}><Check/>Llegó</button><button className="small-button" onClick={() => onAttendance(booking.id, 'no_show')}><X/>No llegó</button></>}{canBook && booking.status === 'reserved' && <button className="small-button danger-text" onClick={() => onCancelBooking(booking)}><Ban/>Cancelar</button>}{canRefund && booking.payment?.status === 'confirmed' && <button className="small-button warning-text" onClick={() => onRefund(booking)}><RotateCcw/>Reembolsar</button>}</div></article>)}{!bookings.length && <Empty title="Sin participantes" text="Todavía no existen reservas para esta clase."/>}</div>{schedule.status === 'scheduled' && <footer>{canBook && <button className="primary" disabled={!schedule.available} onClick={() => onBook(schedule)}><UserPlus/>Reservar miembro</button>}{canManage && <button className="danger-button" onClick={() => onCancelSchedule(schedule)}><Ban/>Cancelar clase</button>}</footer>}</aside>;
}

function Loading() { return <div className="empty compact"><LoaderCircle className="spin"/><strong>Cargando actividades…</strong></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty compact"><Dumbbell/><strong>{title}</strong><span>{text}</span></div>; }
