import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, ArrowDownToLine, ArrowUpFromLine, Ban, Boxes, Check, FileText, LoaderCircle, Plus, Receipt, RotateCcw, ShoppingCart, SlidersHorizontal, X } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useAuth } from '../context/AuthContext';
import { api, apiErrorMessage } from '../services/api';

type Location = { id: string; name: string; is_active: boolean; is_main?: boolean };
type Product = { id: string; name: string; sku: string; description?: string | null; sale_price: number; currency: string; minimum_stock: number; is_active: boolean; current_stock: number };
type Member = { id: string; account_mode: 'portal' | 'managed'; managed_full_name?: string | null; profiles?: { full_name?: string | null } | null };
type Sale = { id: string; location_id: string; location_name: string; member_name: string; seller_name: string; subtotal: number; discount: number; total: number; currency: string; status: 'draft' | 'completed' | 'voided' | 'refunded'; sold_at?: string | null; payment?: { receipt_number: number; payment_method: string; status: string; amount: number; paid_at: string } | null; items: { product_name_snapshot: string; quantity: number; unit_price: number; line_total: number }[] };
type Receipt = { number: number; issuedAt: string; status: string; amount: number; currency: string; paymentMethod: string; externalReference?: string | null; voidReason?: string | null; refundReason?: string | null; reversedAt?: string | null; gym: { name: string; legal_name?: string | null; logo_url?: string | null }; location: { name: string; address?: string | null; city?: string | null }; customer: { name: string; phone?: string | null }; registeredBy: { name: string }; items: { product_name_snapshot: string; quantity: number; unit_price: number; line_total: number }[]; sale: { total: number; discount: number; status: string; sold_at?: string | null } };
type ProductForm = { name: string; sku: string; description: string; salePrice: string; currency: string; minimumStock: string; isActive: boolean };
type AdjustmentForm = { productId: string; movementType: 'purchase' | 'return' | 'adjustment' | 'loss'; quantityDelta: string; reason: string };
type SaleForm = { memberUserId: string; paymentMethod: 'cash' | 'bank_transfer' | 'external_card' | 'external_deuna' | 'other'; externalReference: string; notes: string; discount: string };

const initialProduct: ProductForm = { name: '', sku: '', description: '', salePrice: '', currency: 'USD', minimumStock: '0', isActive: true };
const initialAdjustment: AdjustmentForm = { productId: '', movementType: 'purchase', quantityDelta: '1', reason: '' };
const initialSale: SaleForm = { memberUserId: '', paymentMethod: 'cash', externalReference: '', notes: '', discount: '0' };
const methodLabels: Record<string, string> = { cash: 'Efectivo', bank_transfer: 'Transferencia', external_card: 'Tarjeta', external_deuna: 'Deuna', other: 'Otro' };
const statusLabels: Record<string, string> = { completed: 'Confirmada', voided: 'Anulada', refunded: 'Reembolsada', draft: 'Borrador' };
const movementLabels: Record<string, string> = { purchase: 'Entrada', return: 'Devolución', adjustment: 'Ajuste', loss: 'Pérdida' };
const money = (amount: number, currency: string) => new Intl.NumberFormat('es-EC', { style: 'currency', currency }).format(Number(amount));
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat('es-EC', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const memberName = (member: Member) => member.profiles?.full_name ?? member.managed_full_name ?? 'Miembro';

export function InventoryPage() {
  const { session } = useAuth();
  const queryClient = useQueryClient();
  const role = session?.gymUser?.role;
  const can = (key: string) => role === 'owner' || Boolean(session?.gymUser?.staff_permissions?.some((permission) => permission.permission_key === key && permission.access_mode !== 'denied'));
  const canCatalog = can('products.manage');
  const canAdjust = can('inventory.adjust');
  const canSell = can('sales.register');
  const canReverse = can('sales.void');
  const canMembers = can('members.view');
  const defaultLocationId = session?.gymUser?.default_location_id ?? '';
  const [locationId, setLocationId] = useState(defaultLocationId);
  const [tab, setTab] = useState<'products' | 'sale' | 'history'>('products');
  const [productForm, setProductForm] = useState<ProductForm>(initialProduct);
  const [productTarget, setProductTarget] = useState<Product | null>(null);
  const [adjustmentForm, setAdjustmentForm] = useState<AdjustmentForm>(initialAdjustment);
  const [saleForm, setSaleForm] = useState<SaleForm>(initialSale);
  const [cart, setCart] = useState<Record<string, number>>({});
  const [productModal, setProductModal] = useState(false);
  const [adjustmentModal, setAdjustmentModal] = useState(false);
  const [reversalTarget, setReversalTarget] = useState<{ sale: Sale; action: 'void' | 'refund' } | null>(null);
  const [reversalReason, setReversalReason] = useState('');
  const [receiptId, setReceiptId] = useState<string | null>(null);
  const [error, setError] = useState('');

  const products = useQuery({ queryKey: ['commerce-products', locationId], queryFn: async () => (await api.get<{ products: Product[]; locations: Location[] }>('/inventory/products', { params: { locationId: locationId || undefined, includeInactive: canCatalog } })).data });
  const sales = useQuery({ queryKey: ['commerce-sales', locationId], queryFn: async () => (await api.get<{ sales: Sale[]; locations: Location[] }>('/sales', { params: { locationId: locationId || undefined } })).data });
  const members = useQuery({ queryKey: ['members'], enabled: canMembers, queryFn: async () => (await api.get<{ members: Member[] }>('/members')).data.members });
  const movements = useQuery({ queryKey: ['inventory-movements', locationId], enabled: canAdjust, queryFn: async () => (await api.get<{ movements: { id: string; movement_type: string; quantity_delta: number; stock_after: number; reason: string; created_at: string; product?: { name: string; sku: string } | null; performed_by_name: string }[] }>('/inventory/movements', { params: { locationId: locationId || undefined } })).data.movements });
  const receipt = useQuery({ queryKey: ['sale-receipt', receiptId], enabled: Boolean(receiptId), queryFn: async () => (await api.get<{ receipt: Receipt }>(`/sales/${receiptId}/receipt`)).data.receipt });

  const locationOptions = products.data?.locations ?? sales.data?.locations ?? [];
  const catalogProducts = products.data?.products ?? [];
  const activeProducts = catalogProducts.filter((product) => product.is_active);
  const cartItems = Object.entries(cart).map(([id, quantity]) => ({ product: activeProducts.find((product) => product.id === id), quantity })).filter((item): item is { product: Product; quantity: number } => Boolean(item.product && item.quantity > 0));
  const cartTotal = cartItems.reduce((total, item) => total + Number(item.product.sale_price) * item.quantity, 0);
  const saleTotal = Math.max(0, cartTotal - Number(saleForm.discount || 0));
  const lowStockCount = activeProducts.filter((product) => Number(product.current_stock) <= Number(product.minimum_stock)).length;
  const selectedLocationName = locationOptions.find((location) => location.id === locationId)?.name ?? 'Todas las sucursales';

  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['commerce-products'] }), queryClient.invalidateQueries({ queryKey: ['commerce-sales'] }), queryClient.invalidateQueries({ queryKey: ['inventory-movements'] })]); };
  const createOrUpdate = useMutation({
    mutationFn: async () => {
      const payload = { name: productForm.name, sku: productForm.sku, description: productForm.description || null, salePrice: Number(productForm.salePrice), currency: productForm.currency, minimumStock: Number(productForm.minimumStock), isActive: productForm.isActive };
      return productTarget ? api.patch(`/inventory/products/${productTarget.id}`, payload) : api.post('/inventory/products', payload);
    },
    onSuccess: async () => { setProductModal(false); setProductTarget(null); setProductForm(initialProduct); setError(''); await refresh(); },
    onError: (mutationError) => setError(apiErrorMessage(mutationError)),
  });
  const adjust = useMutation({
    mutationFn: async () => api.post('/inventory/adjustments', { locationId, productId: adjustmentForm.productId, movementType: adjustmentForm.movementType, quantityDelta: Number(adjustmentForm.quantityDelta), reason: adjustmentForm.reason }),
    onSuccess: async () => { setAdjustmentModal(false); setAdjustmentForm(initialAdjustment); setError(''); await refresh(); },
    onError: (mutationError) => setError(apiErrorMessage(mutationError)),
  });
  const checkout = useMutation({
    mutationFn: async () => api.post('/sales', { locationId, memberUserId: saleForm.memberUserId || null, items: cartItems.map((item) => ({ productId: item.product.id, quantity: item.quantity })), discount: Number(saleForm.discount || 0), paymentMethod: saleForm.paymentMethod, externalReference: saleForm.externalReference || null, notes: saleForm.notes || null }),
    onSuccess: async () => { setCart({}); setSaleForm(initialSale); setError(''); setTab('history'); await refresh(); },
    onError: (mutationError) => setError(apiErrorMessage(mutationError)),
  });
  const reverse = useMutation({
    mutationFn: async () => api.patch(`/sales/${reversalTarget?.sale.id}/${reversalTarget?.action}`, { reason: reversalReason }),
    onSuccess: async () => { setReversalTarget(null); setReversalReason(''); setError(''); await refresh(); },
    onError: (mutationError) => setError(apiErrorMessage(mutationError)),
  });

  const openProduct = (product?: Product) => {
    setProductTarget(product ?? null); setProductForm(product ? { name: product.name, sku: product.sku, description: product.description ?? '', salePrice: String(product.sale_price), currency: product.currency, minimumStock: String(product.minimum_stock), isActive: product.is_active } : initialProduct); setError(''); setProductModal(true);
  };
  const addToCart = (product: Product) => setCart((current) => ({ ...current, [product.id]: Math.min((current[product.id] ?? 0) + 1, Math.max(0, Number(product.current_stock))) }));
  const changeQuantity = (productId: string, quantity: number) => setCart((current) => { const next = { ...current }; if (quantity <= 0) delete next[productId]; else next[productId] = quantity; return next; });
  const submitProduct = (event: FormEvent) => { event.preventDefault(); createOrUpdate.mutate(); };
  const submitAdjustment = (event: FormEvent) => { event.preventDefault(); if (locationId && adjustmentForm.productId) adjust.mutate(); };
  const submitSale = (event: FormEvent) => { event.preventDefault(); if (locationId && cartItems.length && saleTotal > 0) checkout.mutate(); };

  return <div className="page commerce-page">
    <div className="page-heading"><div><p className="eyebrow">OPERACIÓN DE RECEPCIÓN</p><h1>STOCK Y VENTAS</h1><p>Controla productos, existencias y ventas sin perder el historial.</p></div><Boxes size={42}/></div>
    {error && <div className="alert error"><span>{error}</span><button className="icon-button" onClick={() => setError('')}><X/></button></div>}
    <section className="panel commerce-toolbar"><label>Sucursal<select value={locationId} onChange={(event) => setLocationId(event.target.value)}><option value="">Todas las sucursales</option>{locationOptions.map((location) => <option key={location.id} value={location.id}>{location.name}{location.is_main ? ' · Principal' : ''}</option>)}</select></label><div className="commerce-summary"><span><Boxes/> {activeProducts.length} productos activos</span><span className={lowStockCount ? 'low-stock' : ''}><Archive/> {lowStockCount} con stock bajo</span><strong>{selectedLocationName}</strong></div></section>
    <section className="panel commerce-panel">
      <div className="directory-tabs"><button className={tab === 'products' ? 'active' : ''} onClick={() => setTab('products')}><Boxes/>Catálogo</button>{canSell && <button className={tab === 'sale' ? 'active' : ''} onClick={() => setTab('sale')}><ShoppingCart/>Nueva venta</button>}<button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}><FileText/>Historial de ventas <span>{sales.data?.sales.length ?? 0}</span></button></div>
      {tab === 'products' && <><div className="commerce-actions"><div><h2>Productos</h2><p>El stock se muestra para la sucursal seleccionada.</p></div><div className="row-actions">{canAdjust && <button className="ghost" disabled={!locationId || !activeProducts.length} onClick={() => setAdjustmentModal(true)}><SlidersHorizontal/>Ajustar stock</button>}{canCatalog && <button className="primary" onClick={() => openProduct()}><Plus/>Nuevo producto</button>}</div></div>{products.isLoading ? <Loading text="Cargando catálogo…"/> : <div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Producto</th><th>SKU</th><th>Precio</th><th>Stock</th><th>Mínimo</th><th>Estado</th><th/></tr></thead><tbody>{catalogProducts.map((product) => <tr key={product.id}><td><strong>{product.name}</strong><small>{product.description || 'Sin descripción'}</small></td><td>{product.sku}</td><td>{money(product.sale_price, product.currency)}</td><td><strong className={Number(product.current_stock) <= Number(product.minimum_stock) ? 'low-stock' : ''}>{product.current_stock}</strong></td><td>{product.minimum_stock}</td><td><span className={`badge ${product.is_active ? 'active' : 'inactive'}`}>{product.is_active ? 'Activo' : 'Inactivo'}</span></td><td>{canCatalog && <button className="small-button" onClick={() => openProduct(product)}>Editar</button>}</td></tr>)}</tbody></table>{!catalogProducts.length && <Empty icon={<Boxes/>} title="Aún no hay productos" text="Crea el primer producto del gimnasio."/>}</div>}</>}
      {tab === 'sale' && canSell && <form className="sale-layout" onSubmit={submitSale}><div><div className="commerce-actions"><div><h2>Nueva venta</h2><p>La venta descuenta el stock de la sucursal al confirmarse.</p></div><span className="sale-total">{money(saleTotal, cartItems[0]?.product.currency ?? 'USD')}</span></div><div className="product-picker">{activeProducts.map((product) => <button type="button" key={product.id} disabled={Number(product.current_stock) < 1} onClick={() => addToCart(product)}><span><strong>{product.name}</strong><small>{money(product.sale_price, product.currency)} · Stock {product.current_stock}</small></span><Plus/></button>)}</div></div><aside className="sale-cart"><h3>Carrito</h3>{cartItems.length ? <>{cartItems.map((item) => <div className="cart-line" key={item.product.id}><span><strong>{item.product.name}</strong><small>{money(item.product.sale_price, item.product.currency)}</small></span><div><button type="button" onClick={() => changeQuantity(item.product.id, item.quantity - 1)}>-</button><b>{item.quantity}</b><button type="button" disabled={item.quantity >= Number(item.product.current_stock)} onClick={() => addToCart(item.product)}>+</button></div></div>)}<label>Cliente opcional<select value={saleForm.memberUserId} onChange={(event) => setSaleForm({ ...saleForm, memberUserId: event.target.value })}><option value="">Venta general</option>{(members.data ?? []).filter((member) => member.account_mode === 'portal' || member.managed_full_name).map((member) => <option key={member.id} value={member.id}>{memberName(member)}</option>)}</select></label><label>Descuento<input type="number" min="0" step="0.01" value={saleForm.discount} onChange={(event) => setSaleForm({ ...saleForm, discount: event.target.value })}/></label><label>Método de pago<select value={saleForm.paymentMethod} onChange={(event) => setSaleForm({ ...saleForm, paymentMethod: event.target.value as SaleForm['paymentMethod'] })}><option value="cash">Efectivo</option><option value="bank_transfer">Transferencia</option><option value="external_card">Tarjeta</option><option value="external_deuna">Deuna</option><option value="other">Otro</option></select></label>{saleForm.paymentMethod !== 'cash' && saleForm.paymentMethod !== 'other' && <label>Referencia<input required value={saleForm.externalReference} onChange={(event) => setSaleForm({ ...saleForm, externalReference: event.target.value })}/></label>}<label>Notas<input value={saleForm.notes} maxLength={1000} onChange={(event) => setSaleForm({ ...saleForm, notes: event.target.value })}/></label><button className="primary full-width" disabled={checkout.isPending || saleTotal <= 0}>{checkout.isPending ? <LoaderCircle className="spin"/> : <Check/>}Confirmar venta</button></> : <div className="empty"><ShoppingCart/><strong>Carrito vacío</strong><span>Selecciona productos para comenzar.</span></div>}</aside></form>}
      {tab === 'history' && <><div className="commerce-actions"><div><h2>Historial de ventas</h2><p>Las anulaciones y reembolsos conservan sus movimientos.</p></div></div>{sales.isLoading ? <Loading text="Cargando ventas…"/> : <div className="sales-list">{(sales.data?.sales ?? []).map((sale) => <article className="sale-row" key={sale.id}><div><strong>{sale.payment?.receipt_number ? `POS-REC-${String(sale.payment.receipt_number).padStart(6, '0')}` : 'Venta'}</strong><small>{dateTime(sale.sold_at)} · {sale.location_name} · {sale.seller_name}</small></div><div><strong>{sale.member_name}</strong><small>{sale.items.map((item) => `${item.product_name_snapshot} ×${item.quantity}`).join(', ')}</small></div><strong>{money(sale.total, sale.currency)}</strong><span className={`badge ${sale.status}`}>{statusLabels[sale.status] ?? sale.status}</span><div className="row-actions"><button className="small-button" onClick={() => setReceiptId(sale.id)}><Receipt/>Recibo</button>{canReverse && sale.status === 'completed' && <><button className="small-button danger-text" onClick={() => setReversalTarget({ sale, action: 'void' })}><Ban/>Anular</button><button className="small-button warning-text" onClick={() => setReversalTarget({ sale, action: 'refund' })}><RotateCcw/>Reembolsar</button></>}</div></article>)}</div>}{!sales.isLoading && !(sales.data?.sales.length) && <Empty icon={<FileText/>} title="Aún no hay ventas" text="Las ventas confirmadas aparecerán aquí."/>}</>}
    </section>
    {canAdjust && movements.data?.length && tab === 'products' ? <section className="panel commerce-movements"><div className="panel-title"><div><h2>Movimientos recientes</h2><p>Historial inmutable de entradas, pérdidas y ajustes.</p></div></div><div className="movement-list">{movements.data.slice(0, 8).map((movement) => <div className="movement-row" key={movement.id}><span className={movement.quantity_delta > 0 ? 'movement-in' : 'movement-out'}>{movement.quantity_delta > 0 ? <ArrowDownToLine/> : <ArrowUpFromLine/>}</span><div><strong>{movement.product?.name ?? 'Producto'}</strong><small>{movementLabels[movement.movement_type] ?? movement.movement_type} · {movement.reason}</small></div><b>{movement.quantity_delta > 0 ? '+' : ''}{movement.quantity_delta}</b><small>{dateTime(movement.created_at)}</small></div>)}</div></section> : null}
    {productModal && <Modal title={productTarget ? 'Editar producto' : 'Nuevo producto'} close={() => setProductModal(false)}><form className="commerce-form" onSubmit={submitProduct}><label>Nombre<input required value={productForm.name} onChange={(event) => setProductForm({ ...productForm, name: event.target.value })}/></label><label>SKU<input required value={productForm.sku} onChange={(event) => setProductForm({ ...productForm, sku: event.target.value })}/></label><label>Descripción<input value={productForm.description} onChange={(event) => setProductForm({ ...productForm, description: event.target.value })}/></label><div className="form-grid"><label>Precio<input required type="number" min="0" step="0.01" value={productForm.salePrice} onChange={(event) => setProductForm({ ...productForm, salePrice: event.target.value })}/></label><label>Stock mínimo<input required type="number" min="0" value={productForm.minimumStock} onChange={(event) => setProductForm({ ...productForm, minimumStock: event.target.value })}/></label></div><label>Moneda<select value={productForm.currency} onChange={(event) => setProductForm({ ...productForm, currency: event.target.value })}><option>USD</option></select></label>{productTarget && <label className="checkbox-line"><input type="checkbox" checked={productForm.isActive} onChange={(event) => setProductForm({ ...productForm, isActive: event.target.checked })}/> Producto activo</label>}<button className="primary full-width" disabled={createOrUpdate.isPending}>{createOrUpdate.isPending ? <LoaderCircle className="spin"/> : <Check/>}Guardar producto</button></form></Modal>}
    {adjustmentModal && <Modal title="Ajustar stock" close={() => setAdjustmentModal(false)}><form className="commerce-form" onSubmit={submitAdjustment}><label>Producto<select required value={adjustmentForm.productId} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, productId: event.target.value })}><option value="">Selecciona un producto</option>{activeProducts.map((product) => <option key={product.id} value={product.id}>{product.name} · Stock {product.current_stock}</option>)}</select></label><label>Tipo<select value={adjustmentForm.movementType} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, movementType: event.target.value as AdjustmentForm['movementType'] })}><option value="purchase">Entrada de compra</option><option value="return">Devolución recibida</option><option value="adjustment">Ajuste manual</option><option value="loss">Pérdida</option></select></label><label>Cantidad {adjustmentForm.movementType === 'loss' ? '(usa número negativo)' : ''}<input required type="number" step="1" value={adjustmentForm.quantityDelta} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, quantityDelta: event.target.value })}/></label><label>Motivo<input required minLength={3} value={adjustmentForm.reason} onChange={(event) => setAdjustmentForm({ ...adjustmentForm, reason: event.target.value })}/></label><button className="primary full-width" disabled={adjust.isPending}>{adjust.isPending ? <LoaderCircle className="spin"/> : <Check/>}Registrar movimiento</button></form></Modal>}
    {reversalTarget && <Modal title={reversalTarget.action === 'void' ? 'Anular venta' : 'Reembolsar venta'} close={() => setReversalTarget(null)}><form className="commerce-form" onSubmit={(event) => { event.preventDefault(); reverse.mutate(); }}><p className="form-note">La venta conservará su historial y devolverá las unidades al stock de la sucursal.</p><label>Motivo<input required minLength={3} value={reversalReason} onChange={(event) => setReversalReason(event.target.value)}/></label><button className="primary full-width" disabled={reverse.isPending}>{reverse.isPending ? <LoaderCircle className="spin"/> : <Check/>}Confirmar</button></form></Modal>}
    {receiptId && <Modal title="Recibo interno de venta" close={() => setReceiptId(null)}>{receipt.isLoading ? <Loading text="Preparando recibo…"/> : receipt.data ? <div className="sale-receipt"><div className="receipt-brand"><div><p className="eyebrow">COMPROBANTE INTERNO</p><h2>{receipt.data.gym.name}</h2><span>{receipt.data.location.name} · POS-REC-{String(receipt.data.number).padStart(6, '0')}</span></div><span className={`badge ${receipt.data.status}`}>{statusLabels[receipt.data.status] ?? receipt.data.status}</span></div><div className="receipt-meta"><span><small>Cliente</small><strong>{receipt.data.customer.name}</strong></span><span><small>Registró</small><strong>{receipt.data.registeredBy.name}</strong></span><span><small>Método</small><strong>{methodLabels[receipt.data.paymentMethod] ?? receipt.data.paymentMethod}</strong></span><span><small>Fecha</small><strong>{dateTime(receipt.data.sale.sold_at)}</strong></span></div><div className="receipt-items">{receipt.data.items.map((item, index) => <div key={`${item.product_name_snapshot}-${index}`}><span>{item.product_name_snapshot} ×{item.quantity}</span><b>{money(item.line_total, receipt.data.currency)}</b></div>)}</div><div className="receipt-total"><span>Total</span><strong>{money(receipt.data.amount, receipt.data.currency)}</strong></div>{(receipt.data.voidReason || receipt.data.refundReason) && <div className="form-note">Motivo: {receipt.data.voidReason ?? receipt.data.refundReason}</div>}<small className="receipt-disclaimer">Comprobante interno. No válido como comprobante tributario.</small></div> : <Empty icon={<FileText/>} title="Recibo no disponible" text="No se pudo cargar el recibo."/>}</Modal>}
  </div>;
}

function Loading({ text }: { text: string }) { return <div className="empty"><LoaderCircle className="spin"/><strong>{text}</strong></div>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="empty">{icon}<strong>{title}</strong><span>{text}</span></div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="modal-backdrop"><div className="modal commerce-modal"><header><div><p className="eyebrow">FITLAB</p><h2>{title}</h2></div><button className="icon-button" onClick={close}><X/></button></header>{children}</div></div>; }
