import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { api,apiErrorMessage } from '../services/api';

type RequestRow={id:string;subscription_id:string;amount:number;currency:string;status:string;payer_name:string;bank_reference:string;paid_on:string;created_at:string;review_reason:string|null;gyms:{name:string};gym_subscriptions:{plan_name_snapshot:string;status:string;current_period_ends_at:string|null}};
const labels:Record<string,string>={pending:'Pendientes',approved:'Aprobados',rejected:'Rechazados',draft:'Sin enviar',all:'Todos'};
export function PlatformBillingPage(){
  const client=useQueryClient(); const [status,setStatus]=useState('pending'); const [page,setPage]=useState(0);
  const [factor,setFactor]=useState(''); const [qr,setQr]=useState(''); const [code,setCode]=useState('');
  const [selection,setSelection]=useState<{row:RequestRow;action:'approved'|'rejected'|'suspend'}|null>(null); const [reason,setReason]=useState('');
  const access=useQuery({queryKey:['platform-billing-access'],queryFn:async()=> (await api.get<{authorized:boolean;verified:boolean}>('/platform/billing/access')).data,retry:false});
  const rows=useQuery({queryKey:['platform-payments',status,page],enabled:!!access.data?.authorized&&!!access.data?.verified,queryFn:async()=> (await api.get<{requests:RequestRow[];total:number}>('/platform/billing/requests',{params:{status,page}})).data});
  const setup=useMutation({mutationFn:async()=>{const {data}=await api.post<{factorId:string;uri?:string}>('/platform/billing/mfa/setup');setFactor(data.factorId);if(data.uri){const QR=await import('qrcode');setQr(await QR.toDataURL(data.uri));}}});
  const verify=useMutation({mutationFn:async()=>{await api.post('/platform/billing/mfa/verify',{factorId:factor,code});setCode('');setQr('');await client.invalidateQueries({queryKey:['platform-billing-access']});}});
  const proof=useMutation({mutationFn:async(id:string)=>{const {data}=await api.post<{url:string}>(`/platform/billing/requests/${id}/proof`);const link=document.createElement('a');link.href=data.url;link.target='_blank';link.rel='noopener noreferrer';link.click();}});
  const review=useMutation({mutationFn:async()=>{if(!selection)return;const {row,action}=selection;await api.post(action==='suspend'?`/platform/billing/subscriptions/${row.subscription_id}/suspend`:`/platform/billing/requests/${row.id}/review`,{decision:action,reason});},onSuccess:async()=>{setSelection(null);setReason('');await client.invalidateQueries({queryKey:['platform-payments']});}});
  const error=access.error??rows.error??setup.error??verify.error??proof.error??review.error;
  return <main className="page" style={{maxWidth:1200,margin:'auto',padding:'2rem 1rem'}}><Link to="/">← Volver a FitLab</Link><div className="page-heading"><div><p className="eyebrow">ADMINISTRACIÓN DE FITLAB</p><h1>Cobros de gimnasios</h1><p>Verifica la acreditación en tu banco antes de aprobar cada pago.</p></div></div>
    {error&&<div className="alert error">{apiErrorMessage(error)}</div>}
    {access.isLoading?<p>Comprobando acceso…</p>:!access.data?.authorized?<section className="panel"><h2>Acceso restringido</h2><p>Esta cuenta no está habilitada para administrar los cobros de FitLab.</p></section>:!access.data.verified?<section className="panel"><h2>Verificación en dos pasos</h2><p>Usa tu aplicación autenticadora para acceder a los comprobantes.</p><button className="primary" disabled={setup.isPending} onClick={()=>setup.mutate()}>Preparar autenticador</button>{qr&&<div><img src={qr} alt="Configura tu autenticador con este QR"/><p>Escanea este código con tu aplicación autenticadora.</p></div>}{factor&&<form onSubmit={e=>{e.preventDefault();verify.mutate();}}><label>Código de seis dígitos<input autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" required maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="primary" disabled={verify.isPending}>Verificar</button></form>}</section>:<>
    <section className="panel"><label>Estado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p>{rows.data?.total??0} solicitudes</p>
    {rows.isLoading?<p>Cargando…</p>:rows.data?.requests.map(row=><article className="panel" key={row.id} style={{marginTop:'1rem'}}><h2>{row.gyms.name}</h2><p>{row.gym_subscriptions.plan_name_snapshot} · {Number(row.amount).toFixed(2)} {row.currency} · {labels[row.status]}</p><p>Orden: {row.id}</p><p>{row.payer_name} · Referencia: {row.bank_reference} · Fecha: {row.paid_on}</p><p>Vigencia: {row.gym_subscriptions.current_period_ends_at?new Date(row.gym_subscriptions.current_period_ends_at).toLocaleDateString('es-EC'):'Sin período pagado'} · {row.gym_subscriptions.status}</p>{row.review_reason&&<p>Revisión: {row.review_reason}</p>}<div className="modal-actions">{row.status!=='draft'&&<button className="ghost" disabled={proof.isPending} onClick={()=>proof.mutate(row.id)}>Descargar comprobante</button>}{row.status==='pending'&&<><button className="primary" onClick={()=>{setReason('');setSelection({row,action:'approved'});}}>Aprobar pago</button><button className="ghost" onClick={()=>{setReason('');setSelection({row,action:'rejected'});}}>Rechazar</button></>}{row.status==='approved'&&row.gym_subscriptions.status!=='suspended'&&<button className="ghost" onClick={()=>{setReason('');setSelection({row,action:'suspend'});}}>Suspender suscripción</button>}</div></article>)}{rows.data?.total===0&&<p>No hay solicitudes con este estado.</p>}
    <div className="modal-actions"><button className="ghost" disabled={page===0} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page+1}</span><button className="ghost" disabled={(page+1)*25>=(rows.data?.total??0)} onClick={()=>setPage(page+1)}>Siguiente</button></div></section>
    {selection&&<div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();review.mutate();}}><h2>{selection.action==='approved'?'Confirmar pago recibido':selection.action==='rejected'?'Rechazar comprobante':'Suspender suscripción'}</h2><p>{selection.row.gyms.name} · {Number(selection.row.amount).toFixed(2)} {selection.row.currency}</p>{selection.action==='approved'&&<p>Confirma únicamente después de comprobar el ingreso en tu banco. Se añadirá un período del plan.</p>}{selection.action==='suspend'&&<p>Se limitarán las operaciones del gimnasio. Sus datos se conservarán.</p>}<label>Motivo o nota de verificación<textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{review.isError&&<div className="alert error">{apiErrorMessage(review.error)}</div>}<div className="modal-actions"><button type="button" className="ghost" disabled={review.isPending} onClick={()=>setSelection(null)}>Cancelar</button><button className="primary" disabled={review.isPending}>Confirmar</button></div></form></div>}</>}
  </main>;
}
